//GET ALL
GET /api/v1/users HTTP/1.1
Host: localhost:4000

###
//GETONE
GET /api/v1/users/clezrzn0q0000ik8wknio6zc3 HTTP/1.1
Host: localhost:4000

###
DELETE /api/v1/users/clezs08z50002ik8w479kw8to HTTP/1.1
Host: localhost:4000

###
//UPDATE
PUT /api/v1/users/clezrzn0q0000ik8wknio6zc3 HTTP/1.1
Host: localhost:4000
Content-Type: application/json
Content-Length: 213

    {
        "email": "pupuce@gmail.com",
        "firstName": "pupuce",
        "lastName": "test",
        "telephone": null,
        "adress": null,
        "town": null,
        "zipCode": null,
    }

###
//SIGNUP
POST /api/v1/auth/signup HTTP/1.1
Host: localhost:4000
Content-Type: application/json

    {
        "firstName": "Laeti2",
        "lastName": "Puce2",
        "email": "Laeti2@gmail.com",
        "telephone": "0612345678",
        "adress": "at home",
        "town": "biarritz",
        "zipCode": "64200",
        "password": "pouet"
    }

###
//SIGNIN
POST /api/v1/auth/signin HTTP/1.1
Host: localhost:4000
Content-Type: application/json

{
    "email": "pupuce@gmail.com",
    "password": "pouet"
}

###
//SIGNOUT
POST /api/v1/auth/signout HTTP/1.1
Host: localhost:4000

###
//DELETE
DELETE /api/v1/tickets/clf4819ke0002ikcef0g3h8mk HTTP/1.1
Host: localhost:4000

###
//UPDATE
POST /api/v1/tickets/clf480wga0001ikcefu47ukqc HTTP/1.1
Host: localhost:4000
Content-Type: application/json

    {
        "title": "Second ticket created and updated"
    }